# Generated by Django 5.1.7 on 2025-04-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='image_url',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
