# Generated by Django 5.1.7 on 2025-04-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_basket_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
