# Generated by Django 5.1.7 on 2025-04-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_basket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='item_count',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='basket',
            name='quantity',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
