# Generated by Django 5.1.7 on 2025-04-24 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
