# Generated by Django 5.1.7 on 2025-04-24 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_orderitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('card_number', models.CharField(max_length=16)),
                ('card_expire_date', models.CharField(max_length=5)),
                ('card_cvv', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Information',
                'verbose_name_plural': 'User Information',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='products.userinfo'),
        ),
    ]
